
#mysql
#mysql
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
  mvc:
    static-path-pattern: /**
  resources:
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/xyz.acproject.blogs?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
    username: user
    #生产环境
    password: 
    #测试环境
    #password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    publickey: 
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2,config
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties:
        druid.stat.mergeSql: true
        druid.stat.slowSqlMillis: 500
        druid.stat.logSlowSql: true
        config.decrypt: true
        config.decrypt.key: ${spring.datasource.publickey}
      # 配置StatFilter
      filter:
        config:
          enabled: true
      web-stat-filter:
        enabled: false
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        #       allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #禁止那些ip
        #                deny: 192.168.1.102
        #是否可以重置
        #启用
        enabled: false
        reset-enable: true
  cache:
    jcache:
      config: classpath:/ehcache.xml
# mybatis
# 对应实体类的包名
mybatis:
  typeAliasesPackage: xyz.acproject.blogs.entity
  # mapper.xml文件所在位置，我放到了resources下面
  mapperLocations: classpath*:mapper/*.xml

#编码格式
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  port: 24452
web:
  upload-path: E:/banqi/blogs/
#-------------end-----------------------------------



#ehcache缓存设置
spring.cache.jcache.config=classpath:/ehcache.xml

#热部署生效
#spring.devtools.restart.enabled: false
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启 //例如静态资源
#spring.devtools.restart.exclude: static/**
#ssl证书
#https加密端口号 443
#server.port=24452
#server.port=8443
#server.ssl.enabled=true
##SSL证书路径 一定要加上classpath:
#server.ssl.key-store=classpath:blogs.acproject.xyz.pfx
##SSL证书密码
#server.ssl.key-store-password=
#证书类型
#server.ssl.key-store-type=JKS
#证书别名K
#server.ssl.keyAlias=blogs.acproject.xyz
